### ISSUE TITLE
Empty string "" is not a valid local name

### ISSUE THREAD

**Issue by silauma** [jugglingcats/tachograph-reader#1]
Hello Guys!
First I want to thank you for your library.
I have wrote a code for reading the file (I downloaded it from DLK Pro TIS-Compact) using your library, but when the code executes the error occurs (see below). What i missed? Many Thanks.

The Error:

System.ArgumentException: Empty string "" is not a valid local name.
   в System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   в System.Xml.XmlWriter.WriteStartElement(String localName)
   в DataFileReader.Region.Process(CustomBinaryReader reader, XmlWriter writer)
   в DataFileReader.DataFile.Process(Stream s, XmlWriter writer)
   в DataFileReader.DataFile.Process(String dataFile, XmlWriter writer)

The code:
```c#
VehicleUnitDataFile MyVehicleUnitDataFile = new VehicleUnitDataFile();
                     
XmlWriterSettings settings = new XmlWriterSettings();
XmlWriter writer = XmlWriter.Create("ddd_data.xml", settings);

writer.WriteStartDocument();
            
MyVehicleUnitDataFile.Process("C:\\Downloads\\M_20141120_1348_H100TM99RUS_XLRTE 78MS0E8889889.DDD", writer);
                    
writer.WriteEndDocument();

writer.Flush();
writer.Close();
```

**Comment by jugglingcats** [comment]
I think the problem is you need to use the static "Create" methods on VehicleUnitDataFile and DriverCardDataFile, not use the 'new' keyword.

Here is the code I use to write to an XML file:

			DataFile vdf=vuFile ? VehicleUnitDataFile.Create() : DriverCardDataFile.Create();

			XmlTextWriter xtw=new XmlTextWriter(MAIN_XML_OUTPUT, Encoding.UTF8);
			try
			{
				xtw.Formatting=Formatting.Indented;
				vdf.Process(fi.FullName, xtw);
			}
			finally
			{
				xtw.Close();
			}

**Comment by silauma** [comment]
It works! Thank you very much.
