### ISSUE TITLE
Refactoring DataFile

### ISSUE THREAD

**Issue by davispuh** [jugglingcats/tachograph-reader#13]
Currently DataFile is really huge and contains several classes.
My proposal would be to split each class in separate files and also split parsing and XML writing in 2 separate steps. That is, create a model for holding data which then can be serialized into any format like XML, JSON or whatever.
My use case is that I don't need XML, but I'm storing parsed data in DB tables.

Would such a PR be accepted?

**Comment by jugglingcats** [comment]
Hi @davispuh thanks for your interest in this code...

No real objection to splitting DataFile.cs into separate files per class. Only issue I can think of is that some people might have local modifications and would find it hard to merge future changes if we do this.

Regarding the intermediate model, is XML not good for this already? You can always attach an XmlWriter to a MemoryStream, and thus have the intermediate results entirely in memory. Otherwise you will have to invent an intermediate format. Unless I'm missing something.

I am thinking perhaps it is time for me to package this code a little more and publish it to NuGet as people seem to be finding it useful. Perhaps any significant refactoring could be part of this effort. See #14.

**Comment by davispuh** [comment]
> Only issue I can think of is that some people might have local modifications and would find it hard to merge future changes if we do this.

It's not that hard to do merging even after such change, besides such changes should be already submitted as PRs. As I don't see any, we can guess no one is planning to upstream code currently. Also it can be used as library so there isn't really much need to modify it locally.

> Regarding the intermediate model, is XML not good for this already? You can always attach an XmlWriter to a MemoryStream, and thus have the intermediate results entirely in memory. 

It's not that efficient, even if it's just in memory, say if I need it as JSON, then parsing goes like `write in XML, read and parse XML, convert to JSON`. This is especially important for some data types like DateTime and say country names (I want them as enum not name string). Which currently would be written as text in XML then read back and parsed again in respective object.
We can avoid this writing/reading/parsing step and keep those objects in memory as C# data types which can be serialized in whatever format user wishes them to be in.

```csharp
	public class ActivityChangeRegion : Region
	{
		byte slot;
		byte status;
		bool inserted;
		Activity activity;
		uint time;
```

Here we already have this intermediate format, it would just be
```csharp
    struct ActivityChange
    {
		public byte slot;
		public byte status;
		public bool inserted;
		public Activity activity;
		public uint time;
    }
```

and we return this ActivityChange struct which can be serialized to any format.

**Comment by jugglingcats** [comment]
I take your point about exposing the datetime and other data types directly. If you have a plan on how to do it and keep the XmlWriter option (as a built-in option) then I'm very happy to consider a pull request! Thanks

**Comment by jugglingcats** [comment]
@davispuh did I close this prematurely? I assumed because pull request was merged this was done.

**Comment by davispuh** [comment]
It's not really done, that #40 PR is only tiny step forward.

Basically if you read my issue
> Currently DataFile is really huge and contains several classes.
My proposal would be to split each class in separate files and also split parsing and XML writing in 2 separate steps. That is, create a model for holding data which then can be serialized into any format like XML, JSON or whatever.

Then can see that first part is done, DataFile is split in several files. But parsing isn't really sperate, you can't parse without creating intermediate XML as there's no model to store data. But I don't think I'll have time for that in nearest future so this can stay closed it doesn't really matter.
