### ISSUE TITLE
Package as assembly and publish to NuGet

### ISSUE THREAD

**Issue by jugglingcats** [jugglingcats/tachograph-reader#14]
Am wondering what users of this code think of this idea? Please use the reaction button to indicate approval, etc. Or feel free to add comments...

Initially I published this code as-is and wasn't sure if anyone would find it useful. There has been some interest, and perhaps this would increase with better packaging.

Would you migrate to a packaged assembly, or do you have significant modifications that would make this difficult? Can your modifications be merged before we package?

**Comment by Picmilinder** [comment]
I found this code very usefulll. I use this code to get data from "ddd" files. I convert finalized Xml file to database. It takes to long, about 60 seconds. Create Xml, take data from Xml and add data to database . The process is to long. I tried to avoid create Xml file,  and add data directly to database, but no success. Thanks for sharing this code.

**Comment by jugglingcats** [comment]
Processing the ddd file to XML should be quite quick, max 3 seconds or so. Depends on your PC of course. If you are seeing more than a few seconds for XML creation, perhaps create a new issue and share a sample file with us. Obviously the database load is not something we can control.

**Comment by jugglingcats** [comment]
Closing for now
