### ISSUE TITLE
Has this code been tested in production environments?

### ISSUE THREAD

**Issue by andreasringdal** [jugglingcats/tachograph-reader#2]
Hi I have tested this project  on a few hundred .ddd files and the results where as expected.   Has this code been used in production and proven stable in actual use?

Andreas

**Comment by jugglingcats** [comment]
Hi, my Godfather shipped the code to a few haulage companies who were using it routinely for analysing their driver and vehicle cards, so I would say yes it has proven stable.

But please be aware that I cannot provide support or warranty of any kind.

Thanks for your interest.
