### ISSUE TITLE
Problem with reading all driver activities

### ISSUE THREAD

**Issue by ddan87** [jugglingcats/tachograph-reader#28]
Hi, I am using your library, and I think it is very useful ;) . 

My problem is that for more .ddd files that I analyze the xml, generated by the library, shows the Node "DataBufferIsWrapperd" set to true. And the xml file doesn't contain all the driver activity of the ddd file.
While if all the activities are present, the label "DataBufferIsWrapperd" is set to false.

What is the problem? Why the data are cut in the xml file?

**Comment by jugglingcats** [comment]
Hi @ddan87 I'm not sure what the problem might be. If you can get me a sample file giving the problem I should be able to take a look. You can email me a link/file at tachographs@mailinator.com.

**Comment by ddan87** [comment]
Hi @jugglingcats , I wrote an email with the file. I'm waiting for news.

**Comment by jugglingcats** [comment]
Hi @ddan87 sorry but mailinator does not support attachments and I don't want to post my private email here. Please could you upload the files somewhere and send me the link. Thanks

**Comment by jugglingcats** [comment]
Hi @ddan87 I got the files thanks. I don't have time to look right now, but from memory the DataBufferIsWrapped is just for information and doesn't indicate an issue, so I we to understand why some of the activity is missing. You are absolutely sure some activity is missing? I would think if there was a general problem with buffer wrapping other people would have reported by now.

**Comment by jugglingcats** [comment]
It looks like this issue might have been introduced by @davispuh in commit https://github.com/jugglingcats/tachograph-reader/commit/74987322484c0c2fe9b9133bb779592982a5196d line 225.

**Comment by ddan87** [comment]
Yes I'm sure some activities are missing. As you can see by the files the ddd have recorded days from 2 May 2017 to 27 Jan 2018, while in xml are present only days from 2 May 2017 to 12 May 2017.

**Comment by ddan87** [comment]
Yes I think the problem is in commit 7498732 line 225.
As I write you in the past email, If I comment the line the library write on the xml all the days of the .ddd, otherwise it gives the problem I explained.

My question now is, this could be the solution? Or it could be give some others bugs?

**Comment by ddan87** [comment]
Sorry for closed and reopened :/

**Comment by davispuh** [comment]
with that change idea was that we don't want to go over cyclicStream twice, like once it's wrapped we don't want to wrap it again 2nd time (prevent infinite loop). Otherwise when `newest` is larger than actually present entries we'll never go out of loop since `if ( pos == newest )` will never be true

In CyclicStream.cs there is
```c#
if ( wrapped )
    throw new EndOfStreamException("Cyclic stream has already wrapped");
```

but for some reason I think it didn't worked.

I'm not really sure, but for now maybe can just remove that case and then later can think how to fix it properly.

**Comment by ddan87** [comment]
Hi @davispuh  thanks for the reply. So the case you say to remove is 
the  _if ( pos == newest )_ 

or the part 

_if (cyclicStream.Wrapped)
  {
     last = true;
  }_

In my analysis commenting this the xml is completed.

**Comment by davispuh** [comment]
Remove 

```c#
if (cyclicStream.Wrapped)
{
	last = true;
}
```

if you remove anything else it wouldn't work...

**Comment by ddan87** [comment]
Thank so much @davispuh. This is exactly what I had made and as I said it work properly. My doubt was if this modify could compromise other part of the code. 
I'm waiting if the bug will be fixed;)

**Comment by jugglingcats** [comment]
I've committed the change discussed. Please update and re-open if any issue!
