### ISSUE TITLE
Unrecognized magic

### ISSUE THREAD

**Issue by DKanarsky** [jugglingcats/tachograph-reader#29]
Hi! I appreciate your work, thanks! But recently i faced trouble with some files. It throws "Unrecognized magic 0xC200 at offset 0x002B".  It's sure not your code's problem but I'm comletely confused. May be you give me some advice where to look.

**Comment by jugglingcats** [comment]
Hi, sorry about this regression issue. I've committed a fix so if you fetch latest code it should be working.

**Comment by jugglingcats** [comment]
Please re-open if issue remains
