### ISSUE TITLE
File not read to the end

### ISSUE THREAD

**Issue by pzaj** [jugglingcats/tachograph-reader#3]
Hello

I'm having an issue where the file (DriverCard) is not read to the end. It's being randomly cut in the middle of either reading or writing to xml, I was not able to locate the issue.

**Comment by andreasringdal** [comment]
Is the file readable in other software?

**Comment by pzaj** [comment]
Yes, it is, using Readesm application.

It does not only fail to read the file, but it does stop in the middle of xml tag. I've tried 4 different files and it happens with all of them. They are legit and correct files from a transport company.

**Comment by jugglingcats** [comment]
Hi are they driver files or vehicle files, and are you definitely using the correct class to read the file, ie:

```
DataFileReader vudf=VehicleUnitDataFile.Create();
DataFileReader dcdf=DriverCardDataFile.Create();
```

If this is all correct and you are still seeing an issue, are you able to share a sample file with us?

**Comment by pzaj** [comment]
These are driver files and I'm using the correct class. I can share them with you I believe, they're pretty old anyway. Would you please give me your email address so I can send them to you? :) 

3 of them are loaded "correctly" - that means they're being cut somewhere in the middle of file. I also tried with vehicle files, but I failed to load it due to invalid character /u0001 somewhere in the file.

I will send them to you asap, but I'm afraid I'll not be able to do this today, I can send them tomorrow morning tho.

**Comment by jugglingcats** [comment]
It may take me a while to look at them too so no rush ;-)

Would rather not put my email here. Can you either attach directly to the issue or upload the files somewhere and post a link (you can remove them later). Thanks

**Comment by pzaj** [comment]
Alright then:

http://s000.tinyupload.com/index.php?file_id=07959668119303443312

Here are four files, three of them are driver cards and one is vu (the one with _vu suffix obviously). Please inform me when you download them, so I can delete them asap.

I will keep looking into that as well, hopefully we can reach a solution soon.

Thanks in advance.

**Comment by jugglingcats** [comment]
I got the files and reproduced the issue - you can delete them.

**Comment by jugglingcats** [comment]
I wrote a little program this morning to convert the ddd files to xml and it ran fine on all of them. I could see the XML was correctly written, complete with end tags. I will post the converted files and source code tonight.

Perhaps you could explain the problem you are seeing a little more and post your code. Are you seeing the XML truncated (ie. end tags not written)? Does it always end in the same place for a given file (you said 'random' in your OP)?

Thanks

**Comment by pzaj** [comment]
Alright, I'll wait for your source code and xml files then and in the meantime I'll give you more detailed explanation along with the link to source code for my application.

But for the record, yes, re-loading a file causes processing to stop randomly, not at the same place every time and it is completely unpredictable to see whether it's gonna close the tag or stop in the middle of a tag (eg "(...)<ActivityC" <= end of processed string).

I also have to say that I do use XmlWriter based on StringBuilder if that matters. I'll post my source code soon.

**Comment by jugglingcats** [comment]
It may just be that you are not flushing/closing the XmlWriter correctly at the end of the process.

**Comment by pzaj** [comment]
Silly me, I was uttermost sure that your code does the flushing and closing! I've adjusted my code to flush and close XmlWriter after processing the file and it now works as expected with each and every file. Thank you very much for solving that issue!

**Comment by jugglingcats** [comment]
No problem hope you find the lib useful!
