### ISSUE TITLE
DriverCard length

### ISSUE THREAD

**Issue by cretbogdan01** [jugglingcats/tachograph-reader#38]
Hi

The DriverCard number has 16 characters in my case. The XML output shows just 14 characters of the driver card number.
Any idea what I need to change to get the full card number ?

Thank you

**Comment by jugglingcats** [comment]
Hi, the card number region is defined in the standard (page 61)...

![image](https://user-images.githubusercontent.com/526349/47367663-0d58bf00-d6d8-11e8-9b38-16bbabb3ff5e.png)

The `cardReplacementIndex` and `cardRenewalIndex` (1 byte each) should appear as attributes in your XML output, but these can't be interpreted as a string.

Hope it helps.

**Comment by cretbogdan01** [comment]
Hi,

Thank you, it helped me.
