### ISSUE TITLE
vuFaultData and VuEventData

### ISSUE THREAD

**Issue by andreasringdal** [jugglingcats/tachograph-reader#4]
You woldn't happen to have any notes layout around regarding  vuFaultData and VuEventData. 
I notice that they are both configured as

     <Padding Name="DataBlock" Size="82"/>

which returns empty elements.

**Comment by jugglingcats** [comment]
Sorry only just noticed this issue!

I don't have any specific notes but looking at the spec, these records shouldn't be too hard to unpack. If you didn't already find it the full spec is here:

http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2002:207:0001:0252:EN:PDF

Looking very briefly at VuEvent collection you have a record structure that looks like this (page 89):

```
VuEventRecord ::= SEQUENCE {
  eventType EventFaultType,
  eventRecordPurpose EventFaultRecordPurpose,
  eventBeginTime TimeReal,
  eventEndTime TimeReal,
  cardNumberDriverSlotBegin FullCardNumber,
  cardNumberCodriverSlotBegin FullCardNumber,
  cardNumberDriverSlotEnd FullCardNumber,
  cardNumberCodriverSlotEnd FullCardNumber,
  similarEventsNumber SimilarEventsNumber
}
```

These are all either existing defined complex types or simple types with defined values in the spec (eg. EventFaultType).

Pull request for VehicleUnitData.config very welcome!
