### ISSUE TITLE
Error getting the System.Security.Cryptography.Asn1 package

### ISSUE THREAD

**Issue by janeliasen** [jugglingcats/tachograph-reader#49]
Hi

I just downloaded the source code and opened it in Visual Studio 2017.  To me it appears that I cannot get the asn1-package. Visual Studio gives me this error: "Unable to find package System.Security.Cryptography.Asn1.Experimental. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org"

Is the package no longer available? I tried using nuget to download the package, but I seem to get an "Not available in this source"-error form the nyget package manager. Am I completely on the wrong path here? Thanks.

**Comment by patientzerouk** [comment]
I found you need to add https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json to your list of NuGet sources - it will then appear, can be installed. 

See https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Security.Cryptography.Asn1.Experimental for some details on the package. 

Hope that helps.

**Comment by janeliasen** [comment]
Thank you very much! :-)

**Comment by malikirmiziten** [comment]
Hi,

I've been trying to use the project, but I encountered an issue with the System.Security.Cryptography.Asn1.Experimental package. When attempting to add the MyGet source (https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json), it redirects to Microsoft's main page instead.

Is this package no longer available? If not, could you suggest an alternative solution or guide me on how to proceed with this issue?

Any help would be greatly appreciated!
