### ISSUE TITLE
Unknown codepage 7

### ISSUE THREAD

**Issue by ramasofficial** [jugglingcats/tachograph-reader#52]
Hello, i'm processing drivers folder and get following error:
![image](https://user-images.githubusercontent.com/36000935/70302514-f9055200-1805-11ea-9979-f56297a9633a.png)

What need to do?

**Comment by ramasofficial** [comment]
My code: 
![image](https://user-images.githubusercontent.com/36000935/70303042-433b0300-1807-11ea-8a04-8328012b2e60.png)

**Comment by ramasofficial** [comment]
I know that is region problem, but my all .ddd files with this problem, how i can to solve it?

**Comment by ramasofficial** [comment]
First unrecognised region with magic 0 at 0x0000

**Comment by patientzerouk** [comment]
Is this a Generation 2 file or corrupted. Some of those errors are just warnings - but the number of unidentified regions suggests gen2 which still a work in progress.

**Comment by ramasofficial** [comment]
![image](https://user-images.githubusercontent.com/36000935/70314232-bfd9db80-181f-11ea-9731-7350e46ba059.png)
No, it is not in progress.

**Comment by ramasofficial** [comment]
Exited with code 0;

**Comment by ramasofficial** [comment]
![image](https://user-images.githubusercontent.com/36000935/70315274-e436b780-1821-11ea-9611-acda02bc7e3c.png)
I get empty xml file

**Comment by patientzerouk** [comment]
Open the file in a hex editor, and let us know what the first two bytes are... 

> No, it is not in progress.
I think you misunderstand. The work for supporting Generation 2 cards is still in progress, not the processing of your file.

**Comment by ramasofficial** [comment]
![image](https://user-images.githubusercontent.com/36000935/70317211-fd416780-1825-11ea-9474-1a833e015475.png)

I can to say my problem, i work in the logistics company, and we want to get DDD files in XML or html format, without readesm program, that we can to read this files and import to program.
I have program now which open reades m and converting, but i want to optimize it.

**Comment by patientzerouk** [comment]
Im not sure at this point - it be useful to see the file, but im not the project maintainer.

**Comment by ramasofficial** [comment]
[0000000000FWY000_Iurie_Gutul_20190901_20191202.zip](https://github.com/jugglingcats/tachograph-reader/files/3931800/0000000000FWY000_Iurie_Gutul_20190901_20191202.zip)

**Comment by patientzerouk** [comment]
I've not had a chance to test this file with the current code, but with an older version it works fine. I can't use the current codebase as I'm busy updating it for GEN2 stuff. 

Do you get a blank XML, or no XML?

**Comment by ramasofficial** [comment]
If we talking about this code:
![image](https://user-images.githubusercontent.com/36000935/70320191-c6228480-182c-11ea-8871-051fdc9e9c2e.png)
I dont get xml code.. or i dont know where need to find it.. because in this folder not xml file

**Comment by patientzerouk** [comment]
Typically, it puts the XML file into the same folder as the DDD file. If its not there, there is a problem. I can't investigate at present, as I'm working on a different file format. Bare with me.

**Comment by Sh0ckwav3** [comment]
hello @ramasofficial,
i've had this problem by myself two weeks ago, i just decomentet the 
`charsetMapping[16] = "ISO-8859-16";` , because this was not a supported.
This solved my problem and now i can read my files (and also yours btw.) with my reader.
i hope it works for you too. 


@patientzerouk ty so much for developing the 2nd gen. support, can you give a forecast when this will be done? If you need help you can contact me, maybe i can help you with something :)

**Comment by ramasofficial** [comment]
Than you peoples, for answers, but i solved it myself.
When i run my project, i don't know how to working C# programming language, because i'm php developer.

But I sat down to this code and solved this problem. This is my code:
![image](https://user-images.githubusercontent.com/36000935/70324663-c4f75480-1838-11ea-965a-1e8d26a63737.png)
I fill path where need to save XML files.

Thank you so much for answer!

**Comment by patientzerouk** [comment]
Great to hear its sorted. Sorry we couldnt help.

> @patientzerouk ty so much for developing the 2nd gen. support, can you give a forecast when this will be done? If you need help you can contact me, maybe i can help you with something :)

Currently I only have access to gen2 vehicle data, so if you have driver files for me to look at that would be great.

As for schedule/timescales, I've just managed to free up time next week to get it done. So by close of play next friday is my hope.

**Comment by Sh0ckwav3** [comment]
Hey @patientzerouk,

I attached you a gen 2 driver file, its just one of our original files, but it doenst store a lot of data sorry.
[C_20191209_0745_Driver_10000000278868.zip](https://github.com/jugglingcats/tachograph-reader/files/3938366/C_20191209_0745_Driver_10000000278868.zip)

I hope it will help you ;)

**Comment by patientzerouk** [comment]
@Sh0ckwav3 Thankyou. I will take a look. I'm trying to finish up the vehicle support and few other things, so here's hoping :-)
