### ISSUE TITLE
Nugget package issue 

### ISSUE THREAD

**Issue by elifmimaroglu** [jugglingcats/tachograph-reader#53]
Hi,
I downloaded the Project which I am very excited about. But unfortunately I faced an nuget issue. 
Fortunately I solved it. I tried to delete the issue. But I couldn't . 
Thank you for your time .

**Comment by davispuh** [comment]
Look here https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Security.Cryptography.Asn1.Experimental
