### ISSUE TITLE
Teltonika FMB640 Tacho protocol

### ISSUE THREAD

**Issue by gjorgoski** [jugglingcats/tachograph-reader#57]
Dear community please let me know if you have available the documentation for implementation of the .ddd remote file download for teltonika FMB640 device.

**Comment by JVanloofsvelt** [comment]
I have, but it is marked as "confidential". Are you purchasing devices from Teltonika directly? If so, you could try asking your Teltonika sales manager.

**Comment by jugglingcats** [comment]
Closing as off-topic
