### ISSUE TITLE
Problem with reading vehicle file

### ISSUE THREAD

**Issue by SatVcd** [jugglingcats/tachograph-reader#6]
Hi, I have problem with attached vehicle DDD file.
It seems that position of any field in binarry structure is wrong and than parsing break on error.
Can you help me, please?
Thank you veru much.

[vehicle.zip](https://github.com/jugglingcats/tachograph-reader/files/737357/vehicle.zip)

**Comment by jugglingcats** [comment]
Hi does it work OK on most of your driver files? I am away at the moment and don't have access to my computer. I will try to look next week but if I forget please comment again and I will see it.

**Comment by jugglingcats** [comment]
Sorry I should have written vehicle files...

**Comment by SatVcd** [comment]
Hi, I found problem in VehicleUnitData.config file.
I must change:
`
<Object Name="SensorPaired">
			<SimpleString Name="SensorSerialNumber" Length="8"/>
`
To:
`
<Object Name="SensorPaired">
      <ExtendedSerialNumber Name="SensorSerialNumber" />
`

Next I found problem with parse month and year in DataFile.cs - ExtendedSerialNumberRegion.
This fields are in BCD format. I correct this inserting two lines:

            month = (byte)((int)((month / 16)) * 10 + (month % 16));
            year = (byte)((int)((year / 16)) * 10 + (year % 16));

Now it works well :-)

Thank you.
I like your library. Great work.

**Comment by jugglingcats** [comment]
Great, I assume these changes are valid for all users of this codebase. Perhaps you could submit a pull request for me to merge?

**Comment by jugglingcats** [comment]
The first change for SensorPaired has been made at some point. I am not sure about the second change, so am going to close this issue for now but people should feel free to re-open or raise another issue if the BCD decoding of dates is wrong -- but please explain carefully the issue!
