### ISSUE TITLE
Need some help 

### ISSUE THREAD

**Issue by karam-fikre** [jugglingcats/tachograph-reader#62]
I want to read the Workshop card data which is also a .DDD file.
Does this project support this type also?

**Comment by rimutaka** [comment]
@karam-fikre , we process workshop cards in our system using this project. Beware that this project does not handle the output of the latest tachograph models. I was supposed to update it to the latest DDD format, including the new signing, but I don't think it's happening any time soon.

**Comment by jugglingcats** [comment]
@rimutaka, I thought the project only handled vehicle and driver cards. Did you have to do anything special to handle workshop cards? V1 cards that is.

**Comment by rimutaka** [comment]
@jugglingcats - I'm not sure now that you said that. If it required a change it was contributed here.
@karam-fikre - sorry, disregard my previous advice, I may be mistaken.

**Comment by davispuh** [comment]
> 
> 
> @rimutaka, I thought the project only handled vehicle and driver cards. Did you have to do anything special to handle workshop cards? V1 cards that is.

they're the same, it parses fine. There might be additional data that's not parsed not sure, but the basic stuff works fine

**Comment by jugglingcats** [comment]
Thanks @davispuh, I had forgotten they are v similar

**Comment by karam-fikre** [comment]
@jugglingcats @davispuh @rimutaka @diogocp 
Thanks for your quick response guys. I'll check the additional data that is needed for the Workshop card.
