### ISSUE TITLE
Parsing digital tachograph files content

### ISSUE THREAD

**Issue by delikelli** [jugglingcats/tachograph-reader#66]
new generation tachograph files can not be read by this reader. configuration files are not compatible with tacho files binary content. do we need new configuration files or different reader project?

**Comment by delikelli** [comment]
I have found pdf document about new generation card and started to develop new library for dtco 4.0. thanks...

**Comment by jugglingcats** [comment]
@delikelli there are plenty of others that would be interested if you felt like sharing...

**Comment by rimutaka** [comment]
... and happy to help too ...
