### ISSUE TITLE
BirthDate of Driver is wrong

### ISSUE THREAD

**Issue by Picmilinder** [jugglingcats/tachograph-reader#7]
When Xml file was created, the Driver birtday is wrong. Please check.
DriverLicense, SpecificConditions and EventsData not shows data, too.
Is there any Solution?
I use this code as dll in VB.NET, 
I hope this is not a issue.

**Comment by jugglingcats** [comment]
Some questions:
- I assume this is driver file, not vehicle file
- Are you able to make a driver file available for testing
- Are you seeing this issue on all your input files or just some of them

If you make a file available, please let me know the expected date.

**Comment by Picmilinder** [comment]
Hello,
It is a driver file. I try both, one DDD and one ESM. The driver birth day is wrong. Real date of birth is 26 may 1958, and in XML file I found  23 jun 1983.
Also, I put some changes in config file, for geting Faults and Even data and I found wrong dated data. I cant get fault and even type. I tried hard but no success. Thanks for your help.

**Comment by Picmilinder** [comment]
...one more notificatio. Event and Fault data Begins in 1.1.1970 and ends 30.01.1987.

**Comment by jugglingcats** [comment]
Please can you make sample file available, otherwise it is hard for me to check anything. From memory the events data is central and working for others so am surprised if there's an issue there, but happy to check your file. You can email the file or a link to tr1 at akirkpatrick dot com.

**Comment by jugglingcats** [comment]
DDD file please...

**Comment by Picmilinder** [comment]
Sent to E-Mail. To get Event and Fault I had to change DriverCardData.config. Anyway, whithout class in DataFille.cs, it is not possible tog get EvenDataRecords.

**Comment by jugglingcats** [comment]
I found and fixed the issue with driver birth date. We were reading a TimeReal which is used elsewhere but the structure here is Datef as per the specification. I've added this to DataFile.cs and modified the config. Please check it and re-open this issue if there is any problem. I will create a new issue for event and fault data in driver files, but won't have time to work on it myself -- if you feel like submitting a pull request that would be great!
