### ISSUE TITLE
Event and Fault sections not processed in Driver files

### ISSUE THREAD

**Issue by jugglingcats** [jugglingcats/tachograph-reader#9]
These are not defined at all in the config for driver files. Pull requests welcome!

**Comment by Picmilinder** [comment]
Works with some issue.
evenBeginTime is TimeReal class, but does not work.  Why is that? TimeReal is simple date format which works in rest of code, exept Events and Faults.

<ElementaryFile Name="EventsData" Identifier="0x0502">
    <Object Name="CardEventData">
       <Repeat Name ="CardEventRecord" CountRef="#NoOfEventsPerType">
          <HexValue Name="eventType" Length="2" />
          <TimeReal Name="eventBeginTime"/>
          <TimeReal Name="eventEndTime"/>
      </Repeat>
    </Object>
  </ElementaryFile>

**Comment by jugglingcats** [comment]
I fixed up the formatting of your comment ;)

I checked the spec for CardEventRecord and the EventFaultType is defined (page 70) as `OCTET STRING(SIZE(1))`, so I think you want `Length="1"` in your config file.

**Comment by Picmilinder** [comment]
Thanks.
On page 59 eventBegintime and eventEndTime are TimeReal. Same problem as DriverBirhtDay. I get wrong dates. likes 30.01.1987. and 1.1.1970.  I tried the format TimeReal in DataFile.cs but nothing.

**Comment by jugglingcats** [comment]
Driver birthday is defined as `Datef` in the spec, not `TimeReal`. I think the problem is that if you define `EventFaultType` as `HexValue` with length 2, you are "pushing" the reader one byte too far, so the alignment when reading the `eventBeginTime` and `eventEndTime` is incorrect, hence the dates in output are wrong.

Try changing:
```
          <HexValue Name="eventType" Length="2" />
```
to
```
          <HexValue Name="eventType" Length="1" />
```
and confirm issue remains. Tx

**Comment by Picmilinder** [comment]
I tried everything, Still same, dates are wrong. I tried other elements like SpecificConditionRecord, that use TimeReal too, and I get perfect data. Events and Faults are mistery.

**Comment by jugglingcats** [comment]
I will try and take a look tonight with your sample file.

**Comment by Picmilinder** [comment]
Thanks, I know you're busy. I appreciate your work.

**Comment by jugglingcats** [comment]
Think I got it all working. Key things to note:

- These sections have a fixed number of "outer" sections as per the spec, and then a number of events of different types
- Quite a lot of different event type sections have no data. In this case you will see event type of 0 and date of 1/1/1970. You will need to filter these out downstream
- The driver file you gave me doesn't have any errors as far as I can tell
- It important when adding to the `.config` files (particularly to repeating sections) that each section is consumed _completely_, otherwise reader will be in the wrong position. In this case you omitted the vehicle registration info
- I put initial caps on your element names as that is the convention

Let me know if I missed anything! I added everything as separate pull requests so hopefully fairly simple for you to merge.

Enjoy

**Comment by Picmilinder** [comment]
Hello,
With that changes I have only duplicated data in Events and Faults. There is no Events. All zeros. The File I sent to you has 4 Events, according to "Tachograph file Viewer LE". Events are: 7.7.2015 at ,6;40 & 7:04,  and 23.08.2106 at 6:59 & 7:00. "Power supply interruption".  So, According to book code for eventType is 08H. May be that is the problem, cause reader read wrong type of code. 
One more think,  CardEventRecord according to book is sequence. Are you sure that "REPEAT" 6 times is good idea? Thanks any way.

**Comment by jugglingcats** [comment]
Hi, here is my output... it shows the 4 events you mention. I don't think there are any faults recorded in the file you sent.

![image](https://cloud.githubusercontent.com/assets/526349/26124457/5efad44c-3a76-11e7-8a92-39050f497cd4.png)

Below is highlighted section of spec regarding the nested "sequence of sets", only two in the case of faults, 6 in the case of card events. Hope it helps.

![image](https://cloud.githubusercontent.com/assets/526349/26124532/b2c01a24-3a76-11e7-8b26-c9cc4b8270b6.png)

**Comment by jugglingcats** [comment]
It would be a nice enhancement to be able to drop (not output) events that have no data, but I don't think it's totally trivial and I _definitely_ don't have time for that :)

**Comment by Picmilinder** [comment]
Yes, that is it. What I am doing wrong then?

**Comment by jugglingcats** [comment]
Are you looking far enough in the file? Note I have collapsed the first three CardEventRecordCollection elements in my screenshot... so the meaningful CardEventRecord appear in the middle of a load of empty ones before and after!

**Comment by Picmilinder** [comment]
YES, FinaIly. Everything is work . Thanks a lot for your time and effort. 
p.s. Please, blur vehicle registration in post above. THANKS, again.

**Comment by jugglingcats** [comment]
Glad it's working. Removed the screen grab with registration!
